module.exports = {
  login: require("./auth/login"),
  logout: require("./auth/logout"),
  signup: require("./auth/signup"),
  getAccessToken: require("./auth/kakao").getAccessToken,
  getUserInfo: require("./auth/kakao").getUserInfo,
  search: require("./actor/actor").search,
  recommendation: require("./actor/recommendation"),
  actorDetail: require("./actor/actorDetail"),
  post: require("./noticeBoard/post"),
  requestActor: require("./noticeBoard/requestActor"),
  updateProfile: require("./mypage/updateProfile"),
  deleteAccount: require("./mypage/deleteAccount"),
  clickFavorite: require("./favorite/clickFavorite"),
  favoriteActor: require("./favorite/favorite").favoriteActor,
  favoriteMovie: require("./favorite/favorite").favoriteMovie,
  deleteFavorite: require("./favorite/favorite").deleteFavorite,
  watchButton: require("./favorite/favorite").watchButton,
};
